# Generated by Django 4.2.3 on 2023-07-26 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_pause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='pause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work.pause'),
        ),
    ]
