# Generated by Django 4.2.3 on 2023-07-28 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_alter_activity_pause'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='pause',
        ),
    ]
