# Generated by Django 4.2.3 on 2023-07-28 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_remove_activity_pause'),
    ]

    operations = [
        migrations.AddField(
            model_name='pause',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work.activity'),
        ),
    ]
