# Generated by Django 4.2.3 on 2023-07-28 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_pause_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pause',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.activity'),
        ),
    ]
