# Generated by Django 4.2.3 on 2023-07-29 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_alter_pause_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pause',
            old_name='activity',
            new_name='user',
        ),
    ]
