# Generated by Django 4.2.3 on 2023-07-31 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_rename_activity_pause_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='name',
        ),
    ]
